name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Use latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Use latest version
        with:
          node-version: 18  # Change if needed

      - name: Install dependencies
        run: npm ci  # More reliable than npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # ✅ Ensure this is v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Use latest version

      - name: Download artifact
        uses: actions/download-artifact@v4  # ✅ Correct action
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # ✅ Correct deployment action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
